/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx_hal.h"
#include "stm32_assert.h"
#include "gpio_driver_hal.h"

//Headers definition
int add(int x, int y);

//Definición de variables para desarrollo de Tercer Punto
uint8_t counteri = 0;
uint8_t decimalInput = 0;
uint8_t decimalInput01 = 0;

//Definición de constantes para desarrollo de Tercer Punto
#define LIMITE_INFERIOR 0
#define LIMITE_SUPERIOR 61

//Definimos Pines a utilizar
GPIO_Handler_t userLed    = {0}; //PinA5
GPIO_Handler_t userLed_00 = {0}; //PinA0
GPIO_Handler_t userLed_01 = {0}; //PinA6
GPIO_Handler_t userLed_02 = {0}; //PinB9
GPIO_Handler_t userLed_03 = {0}; //PinC6
GPIO_Handler_t userLed_04 = {0}; //PinC7
GPIO_Handler_t userLed_05 = {0}; //PinB6
GPIO_Handler_t userLed_06 = {0}; //PinA9

/*
 * The main function, where everything happens
 */
int main(void)
{
    /* Configuramos el pin */
	//NOTA: p en pGPIO indica un counter
	userLed.pGPIOx                        = GPIOA; //Determinando el puerto a utilizar
	userLed.pinConfig.GPIO_PinNumber      = PIN_5;
	userLed.pinConfig.GPIO_PinMode        = GPIO_MODE_OUT;
	userLed.pinConfig.GPIO_PinOutputType  = GPIO_OTYPE_PUSHPULL;
	userLed.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_MEDIUM;
	userLed.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;

	/* Cargamos la configuracion en los registros que gobiernan el puerto */
	gpio_Config(&userLed);
	gpio_WritePin(&userLed,SET);

	/* ++++====== PRIMER PUNTO ======++++ */

	/* a) Errores encontrados en planteamiento inicial:
	 *
	 * 1. Al momento de asignar a la variable pinValue el valor correspondiente al registro
	 *  IDR desplazado un "pinNumber" de veces hacia la izquierda (usando la operacción
	 *  shift "<<") no se obtiene un resultado que permita identificar si la posición
	 *  correspondiente al pin de análisis está o no activa. La anterior conclusión se
	 *  argumenta también con el hecho de que el valor que retorna la función es exactamente
	 *  el resultado del registro IDR modificado de la forma antes mencionada (no se
	 *  procede a interpretar este resultado para encontrar algún camino que garantice la
	 *  respuesta solicitada), lo cual NO brinda la solución específica que se plantea
	 *  debe cumplir la función.
	 *
	 *  2. La asignación "pinValue = pinValue" al final de la función es innecesaria en
	 *  la estructura de la misma, pues estamos asignando un valor ya guardado en la
	 *  variable anteriormente. Al ser esta línea de código redundante se opta por retirarla
	 *  con el fin de contribuir a la construcción de un código más óptimo.
	 */

	/* b) Solución de los errores identificados:
	 *
	 * Lo primero es realizar una operación correcta en el análisis del registro IDR como
	 * herramienta para la determinación del estado del pin en estudio. Para cumplir con
	 * este propósito se sigue la siguiente metodología:
	 *
	 *- Asignar a la variable pinValue el valor del registro IDR.
	 *
	 *- Usar el operador shift ">>" sobre pinValue con un desplazamiento correspondiente
	 *a pinNumber de veces, pues de esta manera podremos conocer si en la posición del pin
	 *número "pinNumber" el IDR guarda el valor de 1 (pin activado) o 0 (pin desactivado).
	 *
	 *- Para que la variable que retorna la función nos informe efectivamente el estado
	 *del pin, se propone un condicional que evalue si el número asociado a
	 *IDR << pinNumber es par (según estructuración de binarios implica que el valor
	 *asignado al bit CERO es 0) o impar (según estructuración de binarios implica que el
	 *valor asignado al bit CERO es 1). En caso de ser el resultado par se establece
	 *pinValue = 0, por el contrario, en caso de ser impar se establece pinValue = 1.
	 *
	 *- La función retorna el valor de pinValue permitiendo interpretar dos posibilidades:
	 * pinValue = 0 -> Pin sujeto a análisis estÁ DESACTIVADO
	 * PinValue = 1 -> Pin sujeto a análisis estÁ ACTIVADO
	 */

	//Llamamos a la función que se desea analizar para corroborar funcionamiento adecuado
	//de la corrección del código.
	gpio_ReadPin(&userLed);

	/* ++++====== FIN PRIMER PUNTO ======++++ */

	/* ++++====== SEGUNDO PUNTO ======++++ */

	/*
	 * Detalle sobre funcionamiento de la función se encuentra en documento gpio_driver_hal.c
	 */

	//Llamamos a la función que se desea analizar
	gpio_TooglePin(&userLed);

	/* ++++====== FIN SEGUNDO PUNTO ======++++ */

	/* ++++====== TERCER PUNTO ======++++ */

	//En primera instancia se define la configuración de los pines a usar:

	/* PinA0 */
	userLed_00.pGPIOx                        = GPIOA; //Determinando el puerto a utilizar
	userLed_00.pinConfig.GPIO_PinNumber      = PIN_0;
	userLed_00.pinConfig.GPIO_PinMode        = GPIO_MODE_OUT;
	userLed_00.pinConfig.GPIO_PinOutputType  = GPIO_OTYPE_PUSHPULL;
	userLed_00.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_MEDIUM;
	userLed_00.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	/* Cargamos la configuracion en los registros que gobiernan el puerto */
	gpio_Config(&userLed_00);

	/* PinA6 */
	userLed_01.pGPIOx                        = GPIOA; //Determinando el puerto a utilizar
	userLed_01.pinConfig.GPIO_PinNumber      = PIN_6;
	userLed_01.pinConfig.GPIO_PinMode        = GPIO_MODE_OUT;
	userLed_01.pinConfig.GPIO_PinOutputType  = GPIO_OTYPE_PUSHPULL;
	userLed_01.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_MEDIUM;
	userLed_01.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	/* Cargamos la configuracion en los registros que gobiernan el puerto */
	gpio_Config(&userLed_01);

	/* PinB9 */
	userLed_02.pGPIOx                        = GPIOB; //Determinando el puerto a utilizar
	userLed_02.pinConfig.GPIO_PinNumber      = PIN_9;
	userLed_02.pinConfig.GPIO_PinMode        = GPIO_MODE_OUT;
	userLed_02.pinConfig.GPIO_PinOutputType  = GPIO_OTYPE_PUSHPULL;
	userLed_02.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_MEDIUM;
	userLed_02.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	/* Cargamos la configuracion en los registros que gobiernan el puerto */
	gpio_Config(&userLed_02);

	/* PinC6 */
	userLed_03.pGPIOx                        = GPIOC; //Determinando el puerto a utilizar
	userLed_03.pinConfig.GPIO_PinNumber      = PIN_6;
	userLed_03.pinConfig.GPIO_PinMode        = GPIO_MODE_OUT;
	userLed_03.pinConfig.GPIO_PinOutputType  = GPIO_OTYPE_PUSHPULL;
	userLed_03.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_MEDIUM;
	userLed_03.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	/* Cargamos la configuracion en los registros que gobiernan el puerto */
	gpio_Config(&userLed_03);

	/* PinC7 */
	userLed_04.pGPIOx                        = GPIOC; //Determinando el puerto a utilizar
	userLed_04.pinConfig.GPIO_PinNumber      = PIN_7;
	userLed_04.pinConfig.GPIO_PinMode        = GPIO_MODE_OUT;
	userLed_04.pinConfig.GPIO_PinOutputType  = GPIO_OTYPE_PUSHPULL;
	userLed_04.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_MEDIUM;
	userLed_04.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	/* Cargamos la configuracion en los registros que gobiernan el puerto */
	gpio_Config(&userLed_04);

	/* PinB6 */
	userLed_05.pGPIOx                        = GPIOB; //Determinando el puerto a utilizar
	userLed_05.pinConfig.GPIO_PinNumber      = PIN_6;
	userLed_05.pinConfig.GPIO_PinMode        = GPIO_MODE_OUT;
	userLed_05.pinConfig.GPIO_PinOutputType  = GPIO_OTYPE_PUSHPULL;
	userLed_05.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_MEDIUM;
	userLed_05.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	/* Cargamos la configuracion en los registros que gobiernan el puerto */
	gpio_Config(&userLed_05);

	/* PinA9 */
	userLed_06.pGPIOx                        = GPIOA; //Determinando el puerto a utilizar
	userLed_06.pinConfig.GPIO_PinNumber      = PIN_9;
	userLed_06.pinConfig.GPIO_PinMode        = GPIO_MODE_OUT;
	userLed_06.pinConfig.GPIO_PinOutputType  = GPIO_OTYPE_PUSHPULL;
	userLed_06.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_MEDIUM;
	userLed_06.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	/* Cargamos la configuracion en los registros que gobiernan el puerto */
	gpio_Config(&userLed_06);

	//Inicalmente planteamos contador que permita cuenta creciente (1 -> 60)

	for(counteri = LIMITE_INFERIOR; counteri < LIMITE_SUPERIOR; counteri ++){

		//Variable que deseamos convertir a binario
		decimalInput = counteri;

		/*Estamos aplicando copia de variable para poder usarla
		en ciclo while sin alterar el filtro de las siguientes
		condiciones sobre la variable original*/
		decimalInput01 = decimalInput;

		// A continuación se verifica si el número es cero

		// A continuación se verifica si el número es uno



	}

	/* ++++====== FIN TERCER PUNTO ======++++ */

	/* Loop forever */
	while(1){

	}
}

/*
 * Esta funcion sirve para detectar problemas de parametros
 * incorrectos al momento de ejecutar el programa
 */
void assert_failed(uint8_t* file, uint32_t line){
	while(1){
		//PROBLEMS...
	}
}
